* 빌드 실패 해결 ``` [14:27:13] Failed to load external module babel-register [14:27:13] Requiring external module babel-core/register [14:27:16] Using gulpfile ~/ionic-pigdata/gulpfile.babel.js [14:27:16] Starting 'default'... [14:27:16] Starting 'webpack'... [14:27:16] Finished 'default' after 101 ms
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./www/app/components/details/details.js
Module not found: Error: Cannot resolve module 'nvd3/build/nv.d3.min.js' in /home/runner/ionic-pigdata/www/app/components/details
resolve module nvd3/build/nv.d3.min.js in /home/runner/ionic-pigdata/www/app/components/details
  looking for modules in /home/runner/ionic-pigdata/node_modules
    /home/runner/ionic-pigdata/node_modules/nvd3 doesn't exist (module as directory)
[/home/runner/ionic-pigdata/node_modules/nvd3]
 @ ./www/app/components/details/details.js 7:0-34
 ```